### ISSUE TITLE
CPE210 wireless signal quality indicator LEDs

### ISSUE THREAD

**Issue by MichaelSasser** [freifunk-westpfalz/site-ffwp#1]
The CPE210/CPE510 has some wireless signal quality indicator LEDs, displaying the received wireless signal strength of the root AP. Since the update of my CPE210 to v2015.1.x, these LEDs don't displaying the received wireless signal strength anymore. Yes, I know, the LEDs are not rocket solid, but helping a lot, align a new installed node. It's bizarre with the node in one hand and an eye on the notebook in the other hand. Could someone confirm that?

**Comment by Little-Ben** [comment]
Michael, please report that in gluon repository. This is only ffwp's site configuration.
